{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# ROCK PAPER SCISSORS GAME"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### How to run the code\n",
    "\n",
    "This is an executable [Jupyter notebook](https://jupyter.org) (don't worry if these terms seem unfamiliar). You can _run_ this notebook and experiment with the code examples in a couple of ways: *using free online resources* (recommended) or *on your computer*.\n",
    "\n",
    "#### Option : Running on your computer locally\n",
    "\n",
    "To run the code on your computer locally, you'll need to set up [Python](https://www.python.org), download the notebook and install the required libraries. We recommend using the [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/) distribution of Python. Click the **Run** button at the top of this page, select the **Run Locally** option, and follow the instructions.\n",
    "\n",
    ">  **Jupyter Notebooks**: This is a [Jupyter notebook](https://jupyter.org) - a document made of _cells_. Each cell can contain code written in Python or explanations in plain English. You can execute code cells and view the results, e.g., numbers, messages, graphs, tables, files, etc. instantly within the notebook. Jupyter is a powerful platform for experimentation and analysis. Don't be afraid to mess around with the code & break things - you'll learn a lot by encountering and fixing errors. You can use the \"Kernel > Restart & Clear Output\" menu option to clear all outputs and start again from the top."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##  _GAME PLAY_"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    ">This game is **USER** versus **COMPUTER** based, so if you want to play have it in mind that you will be playing with the computer. WISH YOU THE BEST OF LUCK. \n",
    "\n",
    "> **ENJOY!**"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "$$**COMPARISON**$$\n",
    "\n",
    "**Rock** vs **Paper** = **Paper Wins , Rock Lose**\n",
    "    \n",
    "**Rock** vs **Scissors** = **Rock Wins , Scissors Lose**\n",
    "        \n",
    "**Scissors** vs **Paper** = **Scissors Wins , Paper Lose**\n",
    "\n",
    "**Rock** vs **Rock** = **A Tie** {REPLAY}\n",
    "        \n",
    "**Scissors** vs **Scissors** = **A Tie** {REPLAY}\n",
    "\n",
    "**Paper** vs **Paper** = **A Tie** {REPLAY}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Please provise your name \n",
      "\n",
      "Enter your name: Favour\n",
      "Welcome To The Game  Favour \n",
      "\n",
      "The number of challenge or times you want to play is  5 \n",
      "\n",
      "Round  1 \n",
      "\n",
      "You can chose between ROCK , PAPER and SCISSORS \n",
      "\n",
      "Enter your choice (in lower case): rock\n",
      "There's a tie\n",
      "Round  2 \n",
      "\n",
      "You can chose between ROCK , PAPER and SCISSORS \n",
      "\n",
      "Enter your choice (in lower case): scissors\n",
      "You win \n",
      " \n",
      "Computer choose  Paper \n",
      "\n",
      "Round  3 \n",
      "\n",
      "You can chose between ROCK , PAPER and SCISSORS \n",
      "\n",
      "Enter your choice (in lower case): paper\n",
      "There's a tie\n",
      "Round  4 \n",
      "\n",
      "You can chose between ROCK , PAPER and SCISSORS \n",
      "\n",
      "Enter your choice (in lower case): rock\n",
      "Computer wins \n",
      " You lose  Favour \n",
      "\n",
      "Computer choose  Paper \n",
      "\n",
      "Round  5 \n",
      "\n",
      "You can chose between ROCK , PAPER and SCISSORS \n",
      "\n",
      "Enter your choice (in lower case): paper\n",
      "Computer wins \n",
      " You lose  Favour \n",
      "\n",
      "Computer choose  Scissors \n",
      "\n",
      "\n",
      "\n",
      "Computer has the most wins, COMPUTER WINS\n"
     ]
    }
   ],
   "source": [
    "import random\n",
    "\n",
    "print(\"Please provise your name \\n\")\n",
    "\n",
    "name = \"\"\n",
    "while name == \"\":\n",
    "    name = input(\"Enter your name: \").capitalize()\n",
    "print(\"Welcome To The Game \",name,\"\\n\")\n",
    "\n",
    "play_time = 1\n",
    "print(\"The number of challenge or times you want to play is \", 5,\"\\n\")\n",
    "\n",
    "wins_user = 0\n",
    "wins_computer = 0  \n",
    "draws = 0\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "while play_time <= 5:\n",
    "    \n",
    "    print(\"Round \", play_time , \"\\n\" )\n",
    "\n",
    "    options = {\n",
    "        \"Rock\":1,\n",
    "        \"Paper\":2,\n",
    "        \"Scissors\":3\n",
    "    }\n",
    "        # Computer Turn\n",
    "\n",
    "    computer_choice = random.randint(1,3)\n",
    "\n",
    "    for index in options:\n",
    "        if options[index] == computer_choice:\n",
    "            computer_option = index\n",
    "\n",
    "    # User's turn\n",
    "    print(\"You can chose between ROCK , PAPER and SCISSORS \\n\")\n",
    "\n",
    "    user_choice = \"\"\n",
    "\n",
    "    while user_choice != \"Rock\" and user_choice != \"Paper\" and user_choice != \"Scissors\":\n",
    "\n",
    "        choice = input(\"Enter your choice (in lower case): \").capitalize()  \n",
    "        user_choice = choice\n",
    "    else:\n",
    "        pass\n",
    "    if user_choice == \"Rock\" or user_choice == \"Paper\" or user_choice == \"Scissors\":\n",
    "\n",
    "        # Compare them\n",
    "        compare = True\n",
    "\n",
    "        while compare:\n",
    "\n",
    "            if computer_option == \"Paper\" and user_choice == \"Rock\":\n",
    "                print(\"Computer wins \\n You lose \",name,\"\\n\")\n",
    "                print(\"Computer choose \", computer_option,\"\\n\")\n",
    "                compare = False\n",
    "                wins_computer += 1\n",
    "            elif computer_option == \"Rock\" and user_choice == \"Scisssors\":\n",
    "                print(\"Computer wins \\n You lose \",name,\"\\n\")\n",
    "                print(\"Computer choose \", computer_option,\"\\n\")\n",
    "                compare = False\n",
    "                wins_computer += 1\n",
    "            elif computer_option == \"Scissors\" and user_choice == \"Paper\":\n",
    "                print(\"Computer wins \\n You lose \",name,\"\\n\")\n",
    "                print(\"Computer choose \", computer_option,\"\\n\")\n",
    "                compare = False\n",
    "                wins_computer += 1\n",
    "            elif computer_option == user_choice:\n",
    "                print(\"There's a tie\")\n",
    "                compare = False\n",
    "                draws += 1\n",
    "            else:\n",
    "                print(\"You win \\n \")\n",
    "                print(\"Computer choose \", computer_option,\"\\n\")\n",
    "                compare = False\n",
    "                wins_user += 1\n",
    "\n",
    "    play_time += 1\n",
    "\n",
    "print(\"\\n\")\n",
    "\n",
    "if wins_computer > wins_user:\n",
    "    print(\"Computer has the most wins, COMPUTER WINS\")\n",
    "elif wins_computer == wins_user:\n",
    "    print(\"Equal Number of wins and one draw. NO WINNER\")\n",
    "else:\n",
    "    print(f\"{name} has the most numbers of wins, {name.upper()} wins\")\n",
    "    \n",
    "    \n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "$$**THANKS FOR PLAYING**$$"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
